### ISSUE TITLE
CMD, add please.

### ISSUE THREAD

**Issue by makc-ar** [AlexWaveDiver/WinShop#2]
WinShop.exe -u data.win
WinShop.exe -r data.win

or mask

Unpack.bat:
for %%a in (_.win) do .\Tools\WinShop.exe -u "%%a" data\
Pack.bat:
for %%a in (_.win) do .\Tools\WinShop.exe -r "%%a" data\

**Comment by AlexWaveDiver** [comment]
Winshop is not an app, but a library. 

If you want to just unpack your winfile, check this out: https://github.com/AlexWaveDiver/UndertaleTools
